[package]
name = "tabularasa"
version = "0.1.0"
edition = "2021"
authors = [
]
publish = false

[dependencies]
miniquad = "0.4.0-alpha.10"
cosmic-text = "0.9.0"

[[bin]]
name = "tabularasa"
path = "src/main.rs"
